myds SEGMENT PARA 'veri'
N 	 DW 10
myds ENDS
myss SEGMENT PARA STACK 'yigin'
	 DW 300 DUP(?)
myss ENDS	
mycs SEGMENT PARA 'kod'
	 ASSUME CS:mycs, SS:myss, DS:myds 

MAIN 	 PROC FAR	 
			PUSH DS					 
			XOR AX,AX
			PUSH AX
			MOV AX,myds
			MOV DS,AX        	;EXE TIPI PROGRAM ICIN SABIT KOD SATIRLARI
			MOV AX,N			;N deki değer AX REGİSTERINA AKTARILIYOR
			PUSH AX				;ALT YORDAMDA KULLANILMAK ÜZERE AX'I STACKE ATIYORUM
			CALL FAR PTR FUNC	;ALT YORDAMI CAGIRIYORUM
			POP AX
			CALL PRINTINT		;CIKAN SONUCU EKRANA YAZDIRIYORUM
MAIN     	ENDP

FUNC	 PROC FAR
			PUSH BP				;STACK UZERINDE GEZINMEK ICIN BASE POINTER KULLANILACAK
			PUSH CX
			MOV BP, SP			;BP DEGERINI STACKTEKI EN UST NOKTAYI GOSTEREN SP DEGERINE ESITLIYORUM	
			MOV CX, [BP+8]      ; CS + OFFSET + 2 RW
			CMP CX, 0			;N'IN 0 KONTROLU
			JA LOOP0
			MOV WORD PTR [BP+8], 0
			POP CX
			POP BP
			RETF
LOOP0:		CMP CX, 2			;N'IN 1 KONTROLU
			JA LOOP1
			MOV WORD PTR [BP+8], 1
			POP CX
			POP BP
			RETF
LOOP1:		PUSH BX				;N DEGERINI BX YAZMACINDA SAKLICAM 
			PUSH AX				;SONUCUM AX YAZMACINDA OLUSACAK
			PUSH DI
			MOV BX, CX
			DEC BX
			PUSH BX
			CALL FUNC         	; FUNC(n-1) HESAPLAMA
			POP AX
			PUSH AX
			CALL FUNC 			; FUNC(FUNC(n-1)) HESAPLAMA
			POP AX				
			MOV DI,AX
			DEC BX
			PUSH BX
			CALL FUNC 			; FUNC(n-2) HESAPLAMA
			POP AX
			INC BX
			SUB BX,AX
			PUSH BX
			CALL FUNC			;FUNC(FUNC-1-FUNC(n-2)) HESAPLAMA
			POP AX
			ADD AX, DI 			;FUNC(FUNC(FUNC-1))+FUNC(FUNC-1-FUNC(n-2)) HESAPLAMA
			MOV [BP+8], AX 		;AX YAZMACIMDA SONUC OLUSTU, SONUCU STACKE ATIYORUM
			POP DI
			POP AX
			POP BX
			POP CX
			POP BP
			RETF
FUNC    	ENDP

PRINTINT 	PROC NEAR			
			PUSH CX
			PUSH DX
			XOR DX,DX			;32 BIT BOLMEDE SONUCU ETKILEMEMESI ICIN DX'I 0 YAPTIK
								;HANE SAYISINI BILMEDIGIMIZ ICIN STACKE 0 LARI DOLDURUP
								;KARAKTERLERI ASCII KARAKTER OLARAK SAKLANACAK
			PUSH DX				
			MOV CX,10
HANELER: 
			DIV CX				;DX:AX = AX/CX    AX = BÖLÜM DX = KALAN 
			ADD DX,'0'			;KALAN DEGERINI ASCII TABLOSUNDA YERINI BULUYORUZ
			PUSH DX				;KALANI STACKTE SAKLA 
			XOR DX,DX
			CMP AX,0			;BÖLEN 0 ISE SAYI BITMIS DEMEKTIR
			JNE HANELER
YAZ_L:
			POP AX				;EKRANA YAZILACAK HANELER STACKTE EN ANLAMLI HANEYI CEKELIM
			CMP AX,0			;HANE 0 ISE YAZDIRILACAK HANE KALMAMISTIR
			JE END_DISP_LOOP	
			PUSH AX
			PUSH DX
			MOV DL,AL
			MOV AH,2
			INT 21H				;AL YAZMACINI YAZDIRIYORUM
			POP DX
			POP AX
			JMP YAZ_L
END_DISP_LOOP:
			POP DX
			POP CX
			RET		
PRINTINT	ENDP		
mycs		ENDS
			END MAIN
